#ifndef BINDINGS_H
#define BINDINGS_H

enum class Binding
{
	QUIT, PAUSE,
	PLAYER_MOVE_UP, PLAYER_MOVE_DOWN, PLAYER_MOVE_LEFT, PLAYER_MOVE_RIGHT,
	PLAYER_FIRE_UP, PLAYER_FIRE_DOWN, PLAYER_FIRE_RIGHT, PLAYER_FIRE_LEFT,
	PLAYER_SLOW
};

#endif // !BINDINGS_H
